# Creates SQL container
services:
  mysql:
    build:
      dockerfile: ./sqlDockerfile
    image: webapp-sql
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'