version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - ./db:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
#    healthcheck:
#      test: "mysql -uroot -proot -e \"SHOW TABLEs LIKE 'counter'\" db"
#      interval: 5s
#      timeout: 10s
#      retries: 5
#      start_period: 20s